spring:
  datasource:
    username:
    password:
    driverClassName: "org.h2.Driver"
    type: org.h2.jdbcx.JdbcDataSource
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:modeling;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL