spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/modeling
  flyway:
    locations: ["classpath:/db/migration"]