spring:
  datasource:
    username: sa
    password:
    driverClassName: "org.h2.Driver"
    type: org.h2.jdbcx.JdbcDataSource
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:modeling10;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  flyway:
    url: jdbc:h2:mem:modeling10;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
